const task_assigned = [
  // Existing Tasks for empId: 22A81A1401
  { taskId: "T001", status: "Completed", empId: "22A81A1401", task: "Design login page UI", date: "30-06-2025", assignedTime: "09:00 AM", priority: "High", description: "Design an intuitive and visually appealing user interface for the login page, focusing on user experience and brand consistency.", },
  { taskId: "T002", status: "Pending", empId: "22A81A1401", task: "Create user registration form", date: "30-06-2025", assignedTime: "10:00 AM", priority: "Normal", description: "Develop the frontend components for the user registration form, ensuring all input validations and error handling are in place.", },
  { taskId: "T003", status: "Completed", empId: "22A81A1401", task: "Fix layout bugs in mobile view", date: "30-06-2025", assignedTime: "11:00 AM", priority: "High", description: "Identify and resolve responsive layout issues specifically on mobile devices for key application pages.", },
  { taskId: "T004", status: "Pending", empId: "22A81A1401", task: "Update team profile section", date: "30-06-2025", assignedTime: "12:00 PM", priority: "Normal", description: "Implement updates to the team profile display section, including new fields and improved visual presentation.", },
  { taskId: "T005", status: "Pending", empId: "22A81A1401", task: "Add Google login integration", date: "01-07-2025", assignedTime: "09:30 AM", priority: "High", description: "Integrate Google OAuth for seamless user login and registration, ensuring secure token handling.", },
  { taskId: "T006", status: "Completed", empId: "22A81A1401", task: "Write unit tests for forms", date: "01-07-2025", assignedTime: "10:45 AM", priority: "Normal", description: "Develop comprehensive unit tests for all form components to ensure data integrity and functionality.", },
  { taskId: "T007", status: "Completed", empId: "22A81A1401", task: "Fix logout redirect bug", date: "01-07-2025", assignedTime: "11:15 AM", priority: "High", description: "Resolve the issue causing incorrect redirection after a user logs out of the application.", },
  { taskId: "T008", status: "Pending", empId: "22A81A1401", task: "Enhance UI accessibility", date: "01-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Improve the accessibility of the user interface by adding ARIA attributes, keyboard navigation, and screen reader compatibility.", },
  { taskId: "T009", status: "Completed", empId: "22A81A1401", task: "Refactor Sidebar component", date: "01-07-2025", assignedTime: "02:15 PM", priority: "Normal", description: "Restructure and optimize the Sidebar component's code for better maintainability and performance.", },
  { taskId: "T010", status: "Completed", empId: "22A81A1401", task: "Optimize dashboard performance", date: "01-07-2025", assignedTime: "03:30 PM", priority: "High", description: "Analyze and implement performance optimizations for the main user dashboard, focusing on load times and data rendering.", },

  // Existing Tasks for empId: 22A81A1402
  { taskId: "T011", status: "Completed", empId: "22A81A1402", task: "Set up MongoDB schema", date: "30-06-2025", assignedTime: "09:15 AM", priority: "High", description: "Define and implement the database schema for MongoDB, including collections and document structures for user and task data." },
  { taskId: "T012", status: "Completed", empId: "22A81A1402", task: "Create API for login", date: "30-06-2025", assignedTime: "10:30 AM", priority: "Normal", description: "Develop a RESTful API endpoint for user authentication and login, ensuring secure password hashing." },
  { taskId: "T013", status: "Pending", empId: "22A81A1402", task: "Add JWT token verification", date: "30-06-2025", assignedTime: "11:45 AM", priority: "High", description: "Implement JSON Web Token (JWT) based authentication for securing API routes and managing user sessions." },
  { taskId: "T014", status: "Completed", empId: "22A81A1402", task: "Build attendance POST endpoint", date: "30-06-2025", assignedTime: "12:30 PM", priority: "High", description: "Create an API endpoint for submitting employee attendance records, including timestamp and employee ID." },
  { taskId: "T015", status: "Pending", empId: "22A81A1402", task: "Integrate email verification", date: "01-07-2025", assignedTime: "09:45 AM", priority: "Normal", description: "Set up email verification flow for new user registrations using a third-party email service." },
  { taskId: "T016", status: "Completed", empId: "22A81A1402", task: "Test POST attendance route", date: "01-07-2025", assignedTime: "10:20 AM", priority: "Normal", description: "Perform thorough testing of the attendance POST API endpoint to ensure data accuracy and error handling." },
  { taskId: "T017", status: "Pending", empId: "22A81A1402", task: "Add leave request endpoint", date: "01-07-2025", assignedTime: "11:40 AM", priority: "High", description: "Develop an API endpoint to handle employee leave requests, including submission and approval mechanisms." },
  { taskId: "T018", status: "Completed", empId: "22A81A1402", task: "Secure API routes with auth", date: "01-07-2025", assignedTime: "01:10 PM", priority: "High", description: "Apply middleware to protect all sensitive API routes with proper authentication and authorization checks." },
  { taskId: "T019", status: "Pending", empId: "22A81A1402", task: "Create payroll data route", date: "01-07-2025", assignedTime: "02:45 PM", priority: "Normal", description: "Design and implement an API route to fetch and manage payroll data, ensuring data privacy." },
  { taskId: "T020", status: "Completed", empId: "22A81A1402", task: "Deploy backend on Render", date: "01-07-2025", assignedTime: "04:00 PM", priority: "Normal", description: "Prepare and deploy the backend application to a cloud platform like Render for production readiness." },

  // Existing Tasks for empId: 22A81A1403
  { taskId: "T021", status: "Completed", empId: "22A81A1403", task: "Create performance chart", date: "30-06-2025", assignedTime: "09:00 AM", priority: "Normal", description: "Develop a visual performance chart for employee metrics using a charting library." },
  { taskId: "T022", status: "Pending", empId: "22A81A1403", task: "Add chart filters by month", date: "30-06-2025", assignedTime: "09:45 AM", priority: "High", description: "Implement filtering options for the performance chart, allowing data visualization by specific months." },
  { taskId: "T023", status: "Completed", empId: "22A81A1403", task: "Build export to PDF button", date: "30-06-2025", assignedTime: "11:00 AM", priority: "High", description: "Create a functionality to export performance reports to PDF format from the dashboard." },
  { taskId: "T024", status: "Pending", empId: "22A81A1403", task: "Integrate Chart.js", date: "30-06-2025", assignedTime: "12:15 PM", priority: "Normal", description: "Incorporate Chart.js library into the frontend to render dynamic and interactive data visualizations." },
  { taskId: "T025", status: "Completed", empId: "22A81A1403", task: "Fix chart label bugs", date: "01-07-2025", assignedTime: "09:30 AM", priority: "Normal", description: "Address and resolve any incorrect or misaligned labels displaying on the generated charts." },
  { taskId: "T026", status: "Pending", empId: "22A81A1403", task: "Sync performance data API", date: "01-07-2025", assignedTime: "10:45 AM", priority: "High", description: "Establish a robust connection and data synchronization between the performance charts and the backend API." },
  { taskId: "T027", status: "Completed", empId: "22A81A1403", task: "Add employee scorecard", date: "01-07-2025", assignedTime: "11:20 AM", priority: "High", description: "Develop a digital scorecard feature to track individual employee performance metrics over time." },
  { taskId: "T028", status: "Pending", empId: "22A81A1403", task: "Test export functionality", date: "01-07-2025", assignedTime: "12:30 PM", priority: "Normal", description: "Thoroughly test the PDF export feature across different browsers and data sets to ensure integrity." },
  { taskId: "T029", status: "Completed", empId: "22A81A1403", task: "Document chart module", date: "01-07-2025", assignedTime: "01:40 PM", priority: "Normal", description: "Create comprehensive documentation for the charting module, including usage, API, and customization options." },
  { taskId: "T030", status: "Pending", empId: "22A81A1403", task: "Fix print style issues", date: "01-07-2025", assignedTime: "03:00 PM", priority: "High", description: "Resolve styling discrepancies and layout problems when printing charts or reports from the application." },

  // Existing Tasks for empId: 22A81A1404
  { taskId: "T031", status: "Completed", empId: "22A81A1404", task: "Create employee delete UI", date: "30-06-2025", assignedTime: "09:20 AM", priority: "High", description: "Design and implement the user interface for deleting employee records from the system." },
  { taskId: "T032", status: "Pending", empId: "22A81A1404", task: "Style remove button", date: "30-06-2025", assignedTime: "10:30 AM", priority: "Normal", description: "Apply consistent styling to the 'Remove Employee' button across all relevant pages." },
  { taskId: "T033", status: "Completed", empId: "22A81A1404", task: "Add delete confirmation modal", date: "30-06-2025", assignedTime: "11:30 AM", priority: "High", description: "Implement a confirmation modal to prevent accidental deletion of employee data." },
  { taskId: "T034", status: "Pending", empId: "22A81A1404", task: "Connect DELETE API", date: "30-06-2025", assignedTime: "12:30 PM", priority: "Normal", description: "Integrate the frontend delete functionality with the backend API endpoint for deleting employee records." },
  { taskId: "T035", status: "Completed", empId: "22A81A1404", task: "Fix bug in employee list", date: "01-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Identify and resolve any bugs affecting the display or interaction of the employee list component." },
  { taskId: "T036", status: "Pending", empId: "22A81A1404", task: "Test delete UI on mobile", date: "01-07-2025", assignedTime: "10:15 AM", priority: "Normal", description: "Conduct thorough testing of the employee deletion user interface on various mobile devices." },
  { taskId: "T037", status: "Completed", empId: "22A81A1404", task: "Write test cases for delete", date: "01-07-2025", assignedTime: "11:45 AM", priority: "High", description: "Develop comprehensive test cases to ensure the reliability and security of the employee deletion feature." },
  { taskId: "T038", status: "Pending", empId: "22A81A1404", task: "Add animation to modal", date: "01-07-2025", assignedTime: "01:10 PM", priority: "Normal", description: "Implement subtle animations for the delete confirmation modal to enhance user experience." },
  { taskId: "T039", status: "Completed", empId: "22A81A1404", task: "Refactor delete function", date: "01-07-2025", assignedTime: "02:30 PM", priority: "High", description: "Optimize and clean up the code for the employee deletion function for better performance and maintainability." },
  { taskId: "T040", status: "Pending", empId: "22A81A1404", task: "Fix API error handling", date: "01-07-2025", assignedTime: "04:00 PM", priority: "Normal", description: "Improve the error handling mechanisms for API calls related to employee data operations." },

  // Existing Tasks for empId: 22A81A1405
  { taskId: "T041", status: "Completed", empId: "22A81A1405", task: "Implement user role permissions", date: "30-06-2025", assignedTime: "09:20 AM", priority: "High", description: "Develop a system to manage user roles and their corresponding permissions within the application." },
  { taskId: "T042", status: "Pending", empId: "22A81A1405", task: "Create role-based access control (RBAC)", date: "30-06-2025", assignedTime: "10:30 AM", priority: "Normal", description: "Set up RBAC to restrict access to certain features or data based on the authenticated user's role." },
  { taskId: "T043", "status": "Completed", empId: "22A81A1405", task: "Design admin dashboard layout", date: "30-06-2025", assignedTime: "11:30 AM", priority: "High", description: "Create the visual layout and structure for the administrative dashboard, optimizing for data management." },
  { taskId: "T044", status: "Pending", empId: "22A81A1405", task: "Develop settings page for roles", date: "30-06-2025", assignedTime: "12:30 PM", priority: "Normal", description: "Build a dedicated settings page where administrators can define and modify user roles and permissions." },
  { taskId: "T045", status: "Completed", empId: "22A81A1405", task: "Write API for role management", date: "01-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Develop backend API endpoints for creating, updating, and deleting user roles." },
  { taskId: "T046", status: "Pending", empId: "22A81A1405", task: "Test RBAC policies rigorously", date: "01-07-2025", assignedTime: "10:15 AM", priority: "Normal", description: "Execute a comprehensive test plan for RBAC to ensure all access rules are correctly enforced and no bypasses exist." },
  { taskId: "T047", status: "Completed", empId: "22A81A1405", task: "Document RBAC implementation", date: "01-07-2025", assignedTime: "11:45 AM", priority: "High", description: "Create detailed technical documentation for the Role-Based Access Control system, including design choices and usage." },
  { taskId: "T048", status: "Pending", empId: "22A81A1405", task: "Add audit logging for access", date: "01-07-2025", assignedTime: "01:10 PM", priority: "Normal", description: "Implement a system to log all access attempts and permission-related actions for security auditing." },
  { taskId: "T049", status: "Completed", empId: "22A81A1405", task: "Review security vulnerabilities", date: "01-07-2025", assignedTime: "02:30 PM", priority: "High", description: "Conduct a security review of the application to identify and mitigate potential vulnerabilities related to access control." },
  { taskId: "T050", status: "Pending", empId: "22A81A1405", task: "Prepare for security audit", date: "01-07-2025", assignedTime: "04:00 PM", priority: "Normal", description: "Organize all security-related documentation and prepare the system for an external security audit." },

  // Existing Tasks for empId: 22A81A1406
  { taskId: "T051", status: "Completed", empId: "22A81A1406", task: "Automate user onboarding tests", date: "30-06-2025", assignedTime: "09:20 AM", priority: "High", description: "Develop automated test scripts for the user registration and onboarding process to ensure smooth user flow." },
  { taskId: "T052", status: "Pending", empId: "22A81A1406", task: "Set up CI/CD pipeline for tests", date: "30-06-2025", assignedTime: "10:30 AM", priority: "Normal", description: "Configure a Continuous Integration/Continuous Deployment pipeline to automatically run tests on code commits." },
  { taskId: "T053", status: "Completed", empId: "22A81A1406", task: "Write regression tests for modules", date: "30-06-2025", assignedTime: "11:30 AM", priority: "High", description: "Create a comprehensive suite of regression tests for core application modules to prevent new changes from breaking existing functionality." },
  { taskId: "T054", status: "Pending", empId: "22A81A1406", task: "Perform performance testing", date: "30-06-2025", assignedTime: "12:30 PM", priority: "Normal", description: "Conduct performance tests to identify bottlenecks and ensure the application can handle expected user loads." },
  { taskId: "T055", status: "Completed", empId: "22A81A1406", task: "Generate test reports daily", date: "01-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Set up automated generation and distribution of daily test reports to the development team." },
  { taskId: "T056", status: "Pending", empId: "22A81A1406", task: "Debug failed automated tests", date: "01-07-2025", assignedTime: "10:15 AM", priority: "Normal", description: "Investigate and resolve issues causing failures in the automated test suite." },
  { taskId: "T057", status: "Completed", empId: "22A81A1406", task: "Train team on new testing tools", date: "01-07-2025", assignedTime: "11:45 AM", priority: "High", description: "Conduct training sessions for the QA team on new automated testing frameworks and tools." },
  { taskId: "T058", status: "Pending", empId: "22A81A1406", task: "Integrate security scanning tools", date: "01-07-2025", assignedTime: "01:10 PM", priority: "Normal", description: "Incorporate automated security vulnerability scanning tools into the CI/CD pipeline." },
  { taskId: "T059", status: "Completed", empId: "22A81A1406", task: "Optimize test execution time", date: "01-07-2025", assignedTime: "02:30 PM", priority: "High", description: "Analyze and refactor test scripts to reduce the overall execution time of the automated test suite." },
  { taskId: "T060", status: "Pending", empId: "22A81A1406", task: "Prepare for UAT phase", date: "01-07-2025", assignedTime: "04:00 PM", priority: "Normal", description: "Organize test plans, environments, and data in preparation for the User Acceptance Testing (UAT) phase." },

  // --- NEW DUMMY TASKS FOR THE REMAINING 10 EMPLOYEES (22A81A1407 to 22A81A1416) ---

  // Tasks for empId: 22A81A1407 (Suresh - Project Manager)
  { taskId: "T061", status: "Completed", empId: "22A81A1407", task: "Finalize Q3 project roadmap", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Collaborate with stakeholders to define and finalize the project roadmap for the third quarter, including key milestones and deliverables." },
  { taskId: "T062", status: "Pending", empId: "22A81A1407", task: "Conduct daily stand-up meeting", date: "02-07-2025", assignedTime: "09:30 AM", priority: "High", description: "Lead the daily project stand-up meeting to review progress, identify blockers, and assign new tasks." },
  { taskId: "T063", status: "Completed", empId: "22A81A1407", task: "Review sprint backlog", date: "02-07-2025", assignedTime: "11:00 AM", priority: "Normal", description: "Assess and prioritize items in the current sprint's backlog, ensuring alignment with project goals." },
  { taskId: "T064", status: "Pending", empId: "22A81A1407", task: "Prepare quarterly performance report", date: "03-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Compile and analyze project performance data for the quarterly report, highlighting achievements and areas for improvement." },
  { taskId: "T065", status: "Completed", empId: "22A81A1407", task: "Client communication update", date: "03-07-2025", assignedTime: "02:00 PM", priority: "Normal", description: "Provide a regular progress update to the client, addressing any concerns and showcasing recent developments." },

  // Tasks for empId: 22A81A1408 (Priya - UI/UX Designer)
  { taskId: "T066", status: "Pending", empId: "22A81A1408", task: "Design new dashboard widgets", date: "02-07-2025", assignedTime: "09:30 AM", priority: "High", description: "Create mockups and interactive prototypes for new dashboard widgets, focusing on data visualization and user interaction." },
  { taskId: "T067", status: "Completed", empId: "22A81A1408", task: "Conduct user research for features", date: "02-07-2025", assignedTime: "11:00 AM", priority: "Normal", description: "Plan and execute user research sessions to gather feedback on proposed new features and design concepts." },
  { taskId: "T068", status: "Pending", empId: "22A81A1408", task: "Refine mobile responsive designs", date: "03-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Iterate and improve the mobile responsiveness of existing designs based on user testing and feedback." },
  { taskId: "T069", status: "Completed", empId: "22A81A1408", task: "Create design system documentation", date: "03-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Document newly established components and guidelines within the design system for team consistency." },
  { taskId: "T070", status: "Pending", empId: "22A81A1408", task: "A/B test new button styles", date: "04-07-2025", assignedTime: "09:00 AM", priority: "Normal", description: "Set up and monitor A/B tests for different button styles to determine the most effective design." },

  // Tasks for empId: 22A81A1409 (Ravi - QA Engineer)
  { taskId: "T071", status: "Completed", empId: "22A81A1409", task: "Test leave request functionality", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Execute comprehensive test cases for the new leave request module, including submission, approval, and rejection flows." },
  { taskId: "T072", status: "Pending", empId: "22A81A1409", task: "Write test plan for payroll module", date: "02-07-2025", assignedTime: "10:30 AM", priority: "High", description: "Develop a detailed test plan for the upcoming payroll management module, covering all scenarios and edge cases." },
  { taskId: "T073", status: "Completed", empId: "22A81A1409", task: "Perform regression testing on build", date: "02-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Conduct full regression testing on the latest application build to ensure no existing functionality has been broken." },
  { taskId: "T074", status: "Pending", empId: "22A81A1409", task: "Log and track new bugs", date: "03-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Identify, document, and track new software defects in the bug tracking system, providing detailed reproduction steps." },
  { taskId: "T075", status: "Completed", empId: "22A81A1409", task: "Review automated test results", date: "03-07-2025", assignedTime: "11:00 AM", priority: "Normal", description: "Analyze the results from daily automated test runs, identifying failures and reporting them to the development team." },

  // Tasks for empId: 22A81A1410 (Swathi - DevOps Engineer)
  { taskId: "T076", status: "Completed", empId: "22A81A1410", task: "Configure Jenkins for CI/CD", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Set up and configure Jenkins server to automate Continuous Integration and Continuous Delivery pipelines for the project." },
  { taskId: "T077", status: "Pending", empId: "22A81A1410", task: "Automate deployment to staging", date: "02-07-2025", assignedTime: "10:30 AM", priority: "High", description: "Develop scripts and configurations to automate the deployment process of the application to the staging environment." },
  { taskId: "T078", status: "Completed", empId: "22A81A1410", task: "Monitor server health and logs", date: "02-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Regularly monitor the health of production servers, analyze logs for anomalies, and report any issues." },
  { taskId: "T079", status: "Pending", empId: "22A81A1410", task: "Implement database backup solution", date: "03-07-2025", assignedTime: "09:30 AM", priority: "High", description: "Design and implement an automated backup and recovery solution for the production database." },
  { taskId: "T080", status: "Completed", empId: "22A81A1410", task: "Optimize Docker images for app", date: "03-07-2025", assignedTime: "11:00 AM", priority: "Normal", description: "Review and optimize the Docker images used for the application to reduce size and improve build times." },

  // Tasks for empId: 22A81A1411 (Kishore - Software Developer)
  { taskId: "T081", status: "Pending", empId: "22A81A1411", task: "Develop notification system", date: "02-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Build a real-time notification system for user updates and system alerts." },
  { taskId: "T082", status: "Completed", empId: "22A81A1411", task: "Integrate payment gateway API", date: "02-07-2025", assignedTime: "01:00 PM", priority: "High", description: "Connect the application with a third-party payment gateway for processing transactions." },
  { taskId: "T083", status: "Pending", empId: "22A81A1411", task: "Implement search functionality", date: "03-07-2025", assignedTime: "09:00 AM", priority: "Normal", description: "Add advanced search capabilities to the employee directory, allowing filtered searches." },
  { taskId: "T084", status: "Completed", empId: "22A81A1411", task: "Write API documentation", date: "03-07-2025", assignedTime: "11:30 AM", priority: "Normal", description: "Create comprehensive documentation for new and existing backend API endpoints using Swagger/OpenAPI." },
  { taskId: "T085", status: "Pending", empId: "22A81A1411", task: "Code review for teammate's branch", date: "04-07-2025", assignedTime: "02:00 PM", priority: "Normal", description: "Conduct a thorough code review for a peer's feature branch, providing constructive feedback." },

  // Tasks for empId: 22A81A1412 (Meena - Automation Tester)
  { taskId: "T086", status: "Completed", empId: "22A81A1412", task: "Automate API testing for new routes", date: "02-07-2025", assignedTime: "09:15 AM", priority: "High", description: "Develop automated test scripts for all newly created backend API endpoints, ensuring data integrity and functionality." },
  { taskId: "T087", status: "Pending", empId: "22A81A1412", task: "Set up UI automation framework", date: "02-07-2025", assignedTime: "11:00 AM", priority: "High", description: "Establish a robust UI automation framework (e.g., Cypress, Playwright) for end-to-end testing." },
  { taskId: "T088", status: "Completed", empId: "22A81A1412", task: "Create performance test scenarios", date: "02-07-2025", assignedTime: "02:00 PM", priority: "Normal", description: "Design various performance test scenarios to simulate high user loads and identify system bottlenecks." },
  { taskId: "T089", status: "Pending", empId: "22A81A1412", task: "Integrate tests with version control", date: "03-07-2025", assignedTime: "10:00 AM", priority: "Normal", description: "Ensure all automated test scripts are properly integrated with the Git version control system." },
  { taskId: "T090", status: "Completed", empId: "22A81A1412", task: "Generate weekly test metrics report", date: "03-07-2025", assignedTime: "03:00 PM", priority: "Normal", description: "Automate the generation of weekly test execution metrics and defect reports." },

  // Tasks for empId: 22A81A1413 (Ajay - UI/UX Designer)
  { taskId: "T091", status: "Pending", empId: "22A81A1413", task: "Design 'Leaves' module UI", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Create wireframes and high-fidelity designs for the new employee leaves management module." },
  { taskId: "T092", status: "Completed", empId: "22A81A1413", task: "Conduct usability testing for HR portal", date: "02-07-2025", assignedTime: "11:30 AM", priority: "Normal", description: "Organize and facilitate usability testing sessions for the HR portal to gather user feedback." },
  { taskId: "T093", status: "Pending", empId: "22A81A1413", task: "Develop new iconography set", date: "03-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Design a new set of custom icons for various application features to enhance visual consistency." },
  { taskId: "T094", status: "Completed", empId: "22A81A1413", task: "Create brand guidelines document", date: "03-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Formalize and document the company's brand guidelines, including typography, color palettes, and logo usage." },
  { taskId: "T095", status: "Pending", empId: "22A81A1413", task: "User flow optimization for onboarding", date: "04-07-2025", assignedTime: "09:30 AM", priority: "Normal", description: "Analyze existing user onboarding flows and propose improvements for a smoother and more intuitive experience." },

  // Tasks for empId: 22A81A1414 (Sindhu - Project Manager)
  { taskId: "T096", status: "Completed", empId: "22A81A1414", task: "Stakeholder meeting for budget review", date: "02-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Lead a meeting with key stakeholders to review the project budget, discuss spending, and approve allocations." },
  { taskId: "T097", status: "Pending", empId: "22A81A1414", task: "Update risk register", date: "02-07-2025", assignedTime: "11:30 AM", priority: "Normal", description: "Review and update the project's risk register, identifying new risks and re-evaluating existing ones." },
  { taskId: "T098", status: "Completed", empId: "22A81A1414", task: "Prepare weekly status report", date: "03-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Compile a comprehensive weekly status report for all ongoing projects, highlighting progress, issues, and next steps." },
  { taskId: "T099", status: "Pending", empId: "22A81A1414", task: "Team capacity planning for next sprint", date: "03-07-2025", assignedTime: "02:00 PM", priority: "Normal", description: "Conduct capacity planning sessions with team leads to allocate resources effectively for the upcoming sprint." },
  { taskId: "T100", status: "Completed", empId: "22A81A1414", task: "Vendor contract negotiation", date: "04-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Negotiate terms and conditions with potential vendors for new project tools and services." },

  // Tasks for empId: 22A81A1415 (Rahul - QA Engineer)
  { taskId: "T101", status: "Pending", empId: "22A81A1415", task: "Perform security penetration testing", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Execute penetration tests to identify security vulnerabilities in the application's backend and frontend." },
  { taskId: "T102", status: "Completed", empId: "22A81A1415", task: "Test API authentication flows", date: "02-07-2025", assignedTime: "11:00 AM", priority: "Normal", description: "Verify the robustness and correctness of all API authentication and authorization mechanisms." },
  { taskId: "T103", status: "Pending", empId: "22A81A1415", task: "Automate end-to-end user flows", date: "03-07-2025", assignedTime: "10:00 AM", priority: "High", description: "Develop and implement automated end-to-end test scenarios for critical user pathways in the application." },
  { taskId: "T104", status: "Completed", empId: "22A81A1415", task: "Review and update test cases", date: "03-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Periodically review and update existing test cases to reflect new features and bug fixes." },
  { taskId: "T105", status: "Pending", empId: "22A81A1415", task: "Prepare test environment for new release", date: "04-07-2025", assignedTime: "09:00 AM", priority: "Normal", description: "Set up and configure the test environment with the latest build and required data for the upcoming release." },

  // Tasks for empId: 22A81A1416 (Deepika - DevOps Engineer)
  { taskId: "T106", status: "Completed", empId: "22A81A1416", task: "Implement container orchestration (Kubernetes)", date: "02-07-2025", assignedTime: "09:00 AM", priority: "High", description: "Set up and configure Kubernetes clusters for scalable and resilient application deployment." },
  { taskId: "T107", status: "Pending", empId: "22A81A1416", task: "Automate infrastructure provisioning (Terraform)", date: "02-07-2025", assignedTime: "11:00 AM", priority: "High", description: "Write Terraform scripts to automate the provisioning and management of cloud infrastructure resources." },
  { taskId: "T108", status: "Completed", empId: "22A81A1416", task: "Set up centralized logging system", date: "02-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Implement a centralized logging solution (e.g., ELK stack) for collecting and analyzing application logs." },
  { taskId: "T109", status: "Pending", empId: "22A81A1416", task: "Configure alerting and monitoring", date: "03-07-2025", assignedTime: "09:30 AM", priority: "High", description: "Set up comprehensive monitoring (e.g., Prometheus, Grafana) and alerting for application and infrastructure health." },
  { taskId: "T110", status: "Completed", empId: "22A81A1416", task: "Optimize database performance", date: "03-07-2025", assignedTime: "01:00 PM", priority: "Normal", description: "Analyze database queries and configurations to identify and implement performance optimization strategies." }
];

module.exports = task_assigned;